services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - appetite_net

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: appetite
      POSTGRES_USER: appetite
      POSTGRES_PASSWORD: change_me
    volumes:
      - appetite_db:/var/lib/postgresql/data
    networks:
      - appetite_net

  backend:
    build:
      context: ./backend
    environment:
      DB_DIALECT: postgresql
      DB_HOST: db
      DB_NAME: appetite
      DB_USER: appetite
      DB_PASSWORD: change_me
    depends_on:
      - db
    networks:
      - appetite_net
    # El puerto 8087 ya no es estrictamente necesario exponerlo al host

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    networks:
      - appetite_net
    # El puerto 8086 ya no es estrictamente necesario exponerlo al host

networks:
  appetite_net:
    external: false

volumes:
  appetite_db:
