services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: appetite
      POSTGRES_USER: appetite
      POSTGRES_PASSWORD: change_me
    volumes:
      - appetite_db:/var/lib/postgresql/data
    networks:
      - appetite_net

  backend:
    build:
      context: ./backend
    environment:
      DB_DIALECT: postgresql
      DB_HOST: db
      DB_NAME: appetite
      DB_USER: appetite
      DB_PASSWORD: change_me
    depends_on:
      - db
    ports:
      - "172.16.0.1:8087:8000"
    networks:
      - appetite_net

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "172.16.0.1:8086:80"
    networks:
      - appetite_net

networks:
  appetite_net:

volumes:
  appetite_db:
